#!/bin/bash 

nextflow run main.nf \
 -resume \
 -profile local,singularity \
 --fastq_dir ../2023_11_OC_preprocessed_reads/trimmed_fastq_R1_only \
 --fastq_pattern "*.trim_{1,2}.fastq.gz" \
 --mapping_samplesheet mapping_samplesheet.txt 
