#!/bin/bash 

fastq_dir=/home/akeene/DC_Combined/read_preprocessing/results/trimmed_fastq

nextflow run main.nf \
 -resume \
 -profile local,singularity \
 --fastq_dir $fastq_dir \
 --fastq_pattern "*.trim_{1,2}.fastq.gz" \
 --mapping_samplesheet mapping_samplesheet.txt 
